version: "3.4"

services:
  security_bot:
    image: kuroru-chan.securitybot:${TAG:-latest}
    build:
      context: Kuroru-chan.SecurityBot/
      dockerfile: Dockerfile 
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      BotConfiguration__BotToken: <BotToken>
      BotConfiguration__Socks5Host: 0.0.0.0
      BotConfiguration__Socks5Port: 1080
    restart: unless-stopped
    container_name: kuroru-chan-securitybot
  